#Based on skript-parser build workflow (https://github.com/SkriptLang/skript-parser/blob/master/.github/workflows/build.yml)
name: Build and Upload

on: push

jobs:
  building:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build project
        run: gradle build

      - name: Upload Build
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: Libraries
          path: build/libs/**